language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

branches:
  only:
    - master

script:
  - phpunit
  - bin/phpspec run -v

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
